### ISSUE TITLE
k3s-armhf:v1.18.12+k3s1-ceph introduces panic with SIGSEGV

### ISSUE THREAD

**Issue by TaichiKageyama** [TaichiKageyama/k3s#1]
**Version:**

- k3s version v1.18.12+k3s1-ceph (62561996)
- k3s-armhf build by arm32v6/golang:1.13.15-alpine3.12

**K3s arguments:**

/usr/local/bin/k3s server --disable servicelb --disable traefik --disable-cloud-controller --disable coredns --disable local-storage --disable metrics-server --node-taint home.test/controlplane=true:NoSchedule --kube-apiserver-arg enable-admission-plugins=PodNodeSelector --kubelet-arg stderrthreshold=ERROR --kubelet-arg system-reserved=cpu=100m,memory=64Mi

**Describe the bug**

k3s-armhf receives SIGSEGV just after it starts.
Other k3s for arm64 and amd64 are no problem.

**To Reproduce**

Just start k3s

**Expected behavior**

No panic

**Actual behavior**

panic

**Additional context / logs**

~~~console
k3s[5254]: I1115 12:58:08.782590    5254 network_policy_controller.go:149] Starting network policy controller
k3s[5254]: panic: runtime error: invalid memory address or nil pointer dereference
k3s[5254]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x28a3cb4]
k3s[5254]: goroutine 20906 [running]:
k3s[5254]: runtime: unexpected return pc for runtime.sigpanic called from 0x28a3cb4
k3s[5254]: stack: frame={sp:0xc96dc4c, fp:0xc96dc64} stack=[0xc96c000,0xc96e000)
k3s[5254]: 0c96dbcc:  05824928  0c96df01  0c96dbf8  02c0f0a0
k3s[5254]: 0c96dbdc:  0004157c <runtime.fatalpanic+80>  00041038 <runtime.gopanic+704>  0c96dbec  00040b00 <runtime.preprintpanics+28>
k3s[5254]: 0c96dbec:  0006de30 <runtime.fatalpanic.func1+0>  0c96dc38  0cb25b20  00041038 <runtime.gopanic+704>
k3s[5254]: 0c96dbfc:  0c96dc04  0c96dbe8  00057df4 <runtime.sigpanic+796>  0c96dc38
k3s[5254]: 0c96dc0c:  031ab9d0  0c96df94  00000004  00000004
k3s[5254]: 0c96dc1c:  02069cd0 <github.com/rancher/k3s/pkg/agent/netpol.(*NetworkPolicyController).Run+84>  1879f080  0c96df50  0cb25b20
k3s[5254]: 0c96dc2c:  00000040  0c96df78  0cb25b34  00000000
k3s[5254]: 0c96dc3c:  02af6e88  16434a60  00000000  00000000
k3s[5254]: 0c96dc4c: <028a3cb4  02c0f0a0  05824928  1879f080
k3s[5254]: 0c96dc5c:  00000008  0cb25b20 >027d855c  00000000
k3s[5254]: 0c96dc6c:  00000000  0c96dcc0  00000005  0c96dcc0
k3s[5254]: 0c96dc7c:  00000000  00000000  13a1ee9d  0cb25b20
k3s[5254]: 0c96dc8c:  00011ac4 <runtime.memequal+0>  027d855c  0206aad0 <github.com/rancher/k3s/pkg/agent/netpol.(*NetworkPolicyController).Sync+9
k3s[5254]: 0c96dc9c:  02071494 <github.com/rancher/k3s/pkg/agent/netpol.cleanupStaleRules+952>  0000000c  1879f000  00000009
k3s[5254]: 0c96dcac:  00000010  00000000  00000000  bfe447b4
k3s[5254]: 0c96dcbc:  0d306db3  0000001e  05a71bf0  038be0f0
k3s[5254]: 0c96dccc:  15bc3320  1505b938  00000005  00000005
k3s[5254]: 0c96dcdc:  00000005  0000000d
k3s[5254]: panic(0x2c0f0a0, 0x5824928)
k3s[5254]:         /usr/local/go/src/runtime/panic.go:722 +0x2c0
k3s[5254]: runtime: unexpected return pc for runtime.sigpanic called from 0x28a3cb4
k3s[5254]: stack: frame={sp:0xc96dc4c, fp:0xc96dc64} stack=[0xc96c000,0xc96e000)
k3s[5254]: 0c96dbcc:  05824928  0c96df01  0c96dbf8  02c0f0a0
k3s[5254]: 0c96dbdc:  0004157c <runtime.fatalpanic+80>  00041038 <runtime.gopanic+704>  0c96dbec  00040b00 <runtime.preprintpanics+28>
k3s[5254]: 0c96dbec:  0006de30 <runtime.fatalpanic.func1+0>  0c96dc38  0cb25b20  00041038 <runtime.gopanic+704>
k3s[5254]: 0c96dbfc:  0c96dc04  0c96dbe8  00057df4 <runtime.sigpanic+796>  0c96dc38
k3s[5254]: 0c96dc0c:  031ab9d0  0c96df94  00000004  00000004
k3s[5254]: 0c96dc1c:  02069cd0 <github.com/rancher/k3s/pkg/agent/netpol.(*NetworkPolicyController).Run+84>  1879f080  0c96df50  0cb25b20
k3s[5254]: 0c96dc2c:  00000040  0c96df78  0cb25b34  00000000
k3s[5254]: 0c96dc3c:  02af6e88  16434a60  00000000  00000000
k3s[5254]: 0c96dc4c: <028a3cb4  02c0f0a0  05824928  1879f080
k3s[5254]: 0c96dc5c:  00000008  0cb25b20 >027d855c  00000000
k3s[5254]: 0c96dc6c:  00000000  0c96dcc0  00000005  0c96dcc0
k3s[5254]: 0c96dc7c:  00000000  00000000  13a1ee9d  0cb25b20
k3s[5254]: 0c96dc8c:  00011ac4 <runtime.memequal+0>  027d855c  0206aad0 <github.com/rancher/k3s/pkg/agent/netpol.(*NetworkPolicyController).Sync+9
k3s[5254]: 0c96dc9c:  02071494 <github.com/rancher/k3s/pkg/agent/netpol.cleanupStaleRules+952>  0000000c  1879f000  00000009
k3s[5254]: 0c96dcac:  00000010  00000000  00000000  bfe447b4
k3s[5254]: 0c96dcbc:  0d306db3  0000001e  05a71bf0  038be0f0
k3s[5254]: 0c96dccc:  15bc3320  1505b938  00000005  00000005
k3s[5254]: 0c96dcdc:  00000005  0000000d
k3s[5254]: runtime.panicmem(...)
k3s[5254]:         /usr/local/go/src/runtime/panic.go:199
k3s[5254]: runtime.sigpanic()
k3s[5254]:         /usr/local/go/src/runtime/signal_unix.go:394 +0x31c
k3s[5254]: created by github.com/rancher/k3s/pkg/agent/netpol.Run
k3s[5254]:         /go/src/github.com/rancher/k3s/pkg/agent/netpol/network_policy.go:36 +0x1a8
systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
~~~

**Comment by TaichiKageyama** [comment]
k3s-armhf binary has been build with armv6/go to avoid the following issues,
- https://github.com/rancher/k3s/issues/494
- https://github.com/rancher/k3s/issues/1092
However, runc issues (https://gitlab.alpinelinux.org/alpine/aports/-/issues/10139) has gone.
Additionally it seems the binary build with arm32v6/golang:1.13.15-alpine3.12 introduces this issue.
So it's time to change the build way to the original way.

The released version works now.
https://github.com/TaichiKageyama/k3s/releases/tag/v1.18.12%2Bk3s1-ceph
